version: "2"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
  slave1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: otomato/jenkins-slave:0.7
